#pragma once 


#define	SPAWNER_PAIN_FADEOUT			2.5
#define	SPAWNER_FADEOUT					1
#define SPAWNER_FADEIN_TIME				0.25

#define	GUARDIAN_PAIN_DELAY				0.25
#define GUARDIAN_RANGE_ATTACK_RANGE		1024
#define GUARDIAN_RANGE_ATTACK_DELAY		7
#define GUARDIAN_CHARGE_ATTACK_RANGE	680
#define GUARDIAN_NUM_PROJECTILES		12

// anim blend times
#define	GUARDIAN_PAIN_TO_IDLE			3
#define GUARDIAN_PAIN_TO_PAIN			3
#define GUARDIAN_SIGHT_TO_IDLE			8
#define	GUARDIAN_MELEE_TO_IDLE			12
#define GUARDIAN_IDLE_TO_PAIN			3
#define GUARDIAN_IDLE_TO_WALK			12
#define GUARDIAN_IDLE_TO_CHARGE			12
#define GUARDIAN_IDLE_TO_MELEE			12
#define	GUARDIAN_IDLE_TO_RANGE			12
#define GUARDIAN_IDLE_TO_SIGHT			12
#define GUARDIAN_IDLE_TO_LOST			12
#define GUARDIAN_WALK_TO_IDLE			12
#define GUARDIAN_WALK_TO_PAIN			3
#define	GUARDIAN_WALK_TO_CHARGE			8
#define	GUARDIAN_CHARGE_TO_WALK			0
#define GUARDIAN_CHARGE_TO_IDLE			12
#define GUARDIAN_CHARGE_TO_PAIN			3
#define GUARDIAN_LOST_TO_IDLE			10
#define GUARDIAN_LOST_TO_PAIN			3
#define GUARDIAN_LOST_TO_WALK			24
#define GUARDIAN_LOST_TO_CHARGE			24
#define GUARDIAN_RANGEATTACK_TO_IDLE	4
#define GUARDIAN_SPAWN_TO_IDLE			4
#define	GUARDIAN_IDLE_TO_SPAWN			4
