	REGISTER_STATE_NAME(STATE_Initialize)							//Reserved message name
	REGISTER_STATE_NAME(STATE_Wander)			//Reserved message name
	REGISTER_STATE_NAME(STATE_Jump)		//Reserved message name
	REGISTER_STATE_NAME(STATE_Move)
	REGISTER_STATE_NAME(STATE_Attack)
	REGISTER_STATE_NAME(STATE_Wound)
	REGISTER_STATE_NAME(STATE_Die)
	REGISTER_STATE_NAME(STATE_FindPath)	
	REGISTER_STATE_NAME(STATE_WalkPath)	
	REGISTER_STATE_NAME(STATE_Idle)	
	REGISTER_STATE_NAME(STATE_Dance)	
	REGISTER_STATE_NAME(STATE_Think)	
	REGISTER_STATE_NAME(STATE_Shutdown)	
	REGISTER_STATE_NAME(STATE_ModeChange)	
	

	