//These message names are processed inside msg.h

REGISTER_MESSAGE_NAME(MSG_NULL)							//Reserved message name
	REGISTER_MESSAGE_NAME(MSG_CHANGE_STATE_DELAYED)			//Reserved message name
	REGISTER_MESSAGE_NAME(MSG_CHANGE_SUBSTATE_DELAYED)		//Reserved message name

	//Add new messages here

	REGISTER_MESSAGE_NAME(MSG_ShowTitle)
	REGISTER_MESSAGE_NAME(MSG_BeginNewGame)

	REGISTER_MESSAGE_NAME(MSG_Attack)
	REGISTER_MESSAGE_NAME(MSG_Damaged)
	REGISTER_MESSAGE_NAME(MSG_Wander)
	REGISTER_MESSAGE_NAME(MSG_Jump)
	REGISTER_MESSAGE_NAME(MSG_Move)
	REGISTER_MESSAGE_NAME(MSG_FindPath)
	REGISTER_MESSAGE_NAME(MSG_WalkPath)
	REGISTER_MESSAGE_NAME(MSG_Idle)
	REGISTER_MESSAGE_NAME(MSG_Think)
	REGISTER_MESSAGE_NAME(MSG_IdleChange)
	REGISTER_MESSAGE_NAME(MSG_ModeChange)

	REGISTER_MESSAGE_NAME(MSG_UnitTestMessage)
	REGISTER_MESSAGE_NAME(MSG_UnitTestMessage2)
	REGISTER_MESSAGE_NAME(MSG_UnitTestMessage3)
	REGISTER_MESSAGE_NAME(MSG_UnitTestBroken)
	REGISTER_MESSAGE_NAME(MSG_UnitTestPing)
	REGISTER_MESSAGE_NAME(MSG_UnitTestAck)
	REGISTER_MESSAGE_NAME(MSG_UnitTestDone)
	REGISTER_MESSAGE_NAME(MSG_UnitTestTimer)
